"""Add accounting subjects and update expenses

Revision ID: 500df5aa4926
Revises: f5a835d7407d
Create Date: 2025-11-19 17:21:53.247733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500df5aa4926'
down_revision = 'f5a835d7407d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'accounting_subjects', ['subject_id'], ['subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
