"""Update models for batch management

Revision ID: 69af37d50c6b
Revises: 79fcfd90d8a8
Create Date: 2025-11-20 08:43:41.694078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69af37d50c6b'
down_revision = '79fcfd90d8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_types',
    sa.Column('expense_type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('expense_type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('expense_entries',
    sa.Column('expense_entry_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('expense_purpose', sa.String(length=100), nullable=True),
    sa.Column('expense_detail', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['expense_type_id'], ['expense_types.expense_type_id'], ),
    sa.PrimaryKeyConstraint('expense_entry_id')
    )
    op.create_table('customer_complaints',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('complaint_date', sa.DateTime(), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('complaint_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['seed_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('supplier_expenses',
    sa.Column('supplier_expense_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('expense_entry_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(precision=2), nullable=False),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_entry_id'], ['expense_entries.expense_entry_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('supplier_expense_id')
    )
    op.create_table('complaint_replies',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.Text(), nullable=False),
    sa.Column('reply_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['customer_complaints.complaint_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_replies')
    op.drop_table('supplier_expenses')
    op.drop_table('customer_complaints')
    op.drop_table('expense_entries')
    op.drop_table('expense_types')
    # ### end Alembic commands ###
