"""Update models with new tables

Revision ID: 79fcfd90d8a8
Revises: 500df5aa4926
Create Date: 2025-11-19 19:59:56.596583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fcfd90d8a8'
down_revision = '500df5aa4926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'seed_batches', ['batch_id'], ['batch_id'])

    with op.batch_alter_table('inventory_flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'seed_batches', ['batch_id'], ['batch_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variety_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'varieties', ['variety_id'], ['variety_id'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('unit_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('unit_code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('units_unit_code_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('units_unit_code_key'), ['unit_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('unit_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('unit_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('variety_id')

    with op.batch_alter_table('inventory_flows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('inventory_balances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
