"""Add OpeningBalanceInventory model

Revision ID: f5a835d7407d
Revises: 
Create Date: 2025-11-19 11:55:35.397039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a835d7407d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ship_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['warehouse_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ship_date')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
